### ISSUE TITLE
`sucessful` misspelt in Jobs dashboard 

### ISSUE THREAD

**Issue by gb0o** [jamesmh/coravelpro#11]
A very minor cleanup. The status column in the Jobs dashboard contains a misspelt word `sucessful`. Should be `successful`.

![image](https://user-images.githubusercontent.com/39327472/63224733-c1997800-c20b-11e9-8e4b-776ed9d7faf7.png)

**Comment by jamesmh** [comment]
Good catch 👍

**Comment by jamesmh** [comment]
Fixed in v 1.2.1 👍

**Comment by gb0o** [comment]
great stuff
