### ISSUE TITLE
How to set up time zones to support localization

### ISSUE THREAD

**Issue by caizhiyuan** [jamesmh/coravelpro#13]
//ConfigureServices   method
 services.Configure<RequestLocalizationOptions>(options => {
                options.DefaultRequestCulture = new Microsoft.AspNetCore.Localization.RequestCulture(new CultureInfo("zh-CN"));
            });

  //Configure   method
   var requestLocalizationOptions = app.ApplicationServices.GetService<IOptions<RequestLocalizationOptions>>().Value;
            app.UseRequestLocalization(requestLocalizationOptions);

The above settings do not work ！！！

How to set up "Coravel" to support localization time zone ？

**Comment by jamesmh** [comment]
Are you looking at making Coravel follow the convention or Coravel Pro?

In both cases, they just use UTC no matter what.

**Comment by jamesmh** [comment]
Depending on what you need it could be a potential feature request...

**Comment by caizhiyuan** [comment]
I use Coravel Pro .

Need the UTC of the local time zone, otherwise there will be a time zone, the set time can not be executed according to the time of the local time zone.

**Comment by caizhiyuan** [comment]
Job Scheduling   START / ENDED AT    Time not in this time zone！

**Comment by jamesmh** [comment]
I'm going to close this. For your case, you would need to figure out programatically what the correct UTC time is to schedule.
