### ISSUE TITLE
It's support .NET Core 3.0 ?

### ISSUE THREAD

**Issue by cashwu** [jamesmh/coravelpro#14]
I use .NET Core 3.0.0-preview8, dashboard can't display

**Comment by jamesmh** [comment]
Coravel should. It worked with some of the latest preview versions.

Are you having issues?

**Comment by caizhiyuan** [comment]
When can I support 3.0？
dashboard can't display！

**Comment by jamesmh** [comment]
Sorry, with Coravel Pro the same issue found here applies: https://github.com/jamesmh/coravel/issues/115

**Comment by jamesmh** [comment]
I'm going to be adding support for 3.0 -> moved to this issue https://github.com/jamesmh/coravelpro/issues/18
