### ISSUE TITLE
Schedule have fail message

### ISSUE THREAD

**Issue by cashwu** [jamesmh/coravelpro#15]
Schedule task has success and finished, but get a fail message

![image](https://user-images.githubusercontent.com/4278751/64139853-f1b06000-ce34-11e9-9872-73462f67fb4e.png)

Using Coravel (not pro), not the fail message

**Comment by jamesmh** [comment]
This should be in the other repo: https://github.com/jamesmh/coravel.

Try this from the docs to see if you can track down the error: https://docs.coravel.net/Scheduler/#global-error-handling
