### ISSUE TITLE
.NET Core 3.0 Support

### ISSUE THREAD

**Issue by jamesmh** [jamesmh/coravelpro#18]

**Comment by jamesmh** [comment]
Coravel Pro will have to move from targeting 2.1 to 3.0 explicitly - I thought I could multi-target. Sooo will wait until 3.1 as LTS

**Comment by tehZeno** [comment]
@jamesmh this issue is closed as you are waiting for 3.1 LTS. 
In the meantime any work around to at least get the CRUD dashboard working? :)
