### ISSUE TITLE
Dashboard 404

### ISSUE THREAD

**Issue by justusburger** [jamesmh/coravelpro#2]
Hi, 

I'm trying to get Pro up and running as a trial but after following the installation instructions on https://www.docs.pro.coravel.net/Installation/ and browsing to `/Coravel/Dashboard/` I get a 404.

<img width="758" alt="Screenshot 2019-06-15 at 22 03 07" src="https://user-images.githubusercontent.com/4091173/59556023-57bae300-8fbc-11e9-8e96-4a4eec2cc049.png">

<img width="929" alt="Screenshot 2019-06-15 at 22 03 49" src="https://user-images.githubusercontent.com/4091173/59556028-5db0c400-8fbc-11e9-88cd-82523d9172d7.png">

**Comment by jamesmh** [comment]
Try adding `UseCoravelPro()` after `UseMvc()` and let me know if that works 👍

**Comment by justusburger** [comment]
Yeah I tried moving everything around, but no dice. This is an AspNetCore 2.2 project. My DbContext is in a separate project; not sure if that’s relevant.

**Comment by justusburger** [comment]
Do you perhaps have a sample project with it already installed that I can just clone?

**Comment by justusburger** [comment]
Haha ok so I set up a quick bare bones sample to test it out again and now it works exactly as expected. So it's obviously an issue on my side, which I'll try to find.

Sample repo: https://github.com/justusburger/coravel-pro-sample

Thanks for the amazing work James, I'll be sure to give credit where it's due.💲

**Comment by justusburger** [comment]
Ok so after further investigation I found this seem to be necessary for the dashboard to work:
![Screenshot 2019-06-16 at 12 59 58](https://user-images.githubusercontent.com/4091173/59563192-cf2d5880-9036-11e9-82ca-b34d8eb91e77.png)

**Comment by jamesmh** [comment]
Great 👍
