### ISSUE TITLE
Software Issue (Does not detect end of process)

### ISSUE THREAD

**Issue by lgoehrs** [jamesmh/coravelpro#21]
Hello,

I am using .NEt Core v3.0 (MVC)

I love your software, and would love to purchase a licence, but facing two issues:
- Is there a way to integrate logging and progress so it appears in the dashboard ?

When I launch a very simple process:

  public EBPInvoicesManagement(IConfiguration Configuration)
        {
            myService = new GP_App_Services(Configuration);
        }

        public Task Invoke()
        {
            System.Threading.Thread.Sleep(5000);

            return (Task.CompletedTask);
     }
}

it will not detect the end of the process and will stay in "Running state" in the dashboard.

Kind regards

**Comment by lgoehrs** [comment]
Update: It seems that Scheduled jobs is fine, only when ran manually, that there is a pb.

**Comment by jamesmh** [comment]
It mostly likely due to using Coravel Pro with .NET Core v. 3

I'll be looking to release a new version of Coravel Pro that supports 3.1+ but won't be backward compatible due to changes between 2.2 and 3.0+.

That being said, what database are you using?

**Comment by jamesmh** [comment]
.NET core 3.0 is supported now #24

That should fix any issues you were having 👍

https://www.docs.pro.coravel.net/Installation/#net-core-3-0
