### ISSUE TITLE
Customization While Scheduling

### ISSUE THREAD

**Issue by SailorTurkey** [jamesmh/coravelpro#23]
I am currently evaluating pro, it solves a lot of problems yet falls short in a lot of places, like 
1. one has to publish new invocables to prod environment to create new schedules, needs some dynamic update there. 
2. can't use / schedule same invocable multiple times (more on this later)
3. can't schedule via portal using 'parameters', one has to code in all details in invocable class. 
4. can't filter scheduler logging to 'warning' and up only. (every second running successful jobs hogging memory/disk and destroying db performance)

I was looking for a solution that would let me schedule web api calls. In coravel's terms, i thought i could create a single "WebApiCaller" invocable, with json parameters (see 3). schedule it "Multiple" times (see 2), and have an MVP to start our scheduling requirements.

Is there a plan to create such support for this in foreseeable future or should i just pass coravel?

**Comment by jamesmh** [comment]
1. You can schedule the same job/invocable multiple times with different schedules if you want (that's a big reason of why the UI is helpful). If you need to do **totally different work** then it makes sense to create a new invocable that represents that work.

2. You can schedule the **same** invocable under different schedules - that's what the indicator here is for showing:

![image](https://user-images.githubusercontent.com/7213174/71374649-d8712200-2591-11ea-838f-1020f9647797.png)

3. You are correct, there currently is no way to pass parameters to an invocable. This is a [feature in-progress right now on the main repository for Coravel](https://github.com/jamesmh/coravel/issues/128). Once it's worked out then it can be augmented in Coravel Pro.

4. That's a potential feature request 😊


Your scenario would be possible given the features required above. I don't expect to get much work done during the holidays but most likely once the new year hits these are issues I'll start addressing 👍
