### ISSUE TITLE
Coravel Dashboard gives 401 error

### ISSUE THREAD

**Issue by SuheylZ** [jamesmh/coravelpro#26]
I have been able to run coravel pro. However whenever I try to hit the url :

http://127.0.0.1:5000/coravel/dashboard

it gives me this: 

**This page isn’t working. If the problem continues, contact the site owner.
HTTP ERROR 401**

so what do I need to do in this case? 
This project is a webapi project and we also use Swagger that runs fine. I'm using app.UseCoravelPro() as the very first line for **IApplicationBuilder**

**Comment by jamesmh** [comment]
401 is an authentication error. Did you setup any authentication around that page / Coravel Pro?

Also, what version of .NET Core is this?

**Comment by jamesmh** [comment]
Did you add `services.AddCoravelPro(typeof(ApplicationDbContext));` to `ConfigureServices` too?

Also, put `UseCoravelPro()` at the end of the `Configure` method - that might fix it since it relies on other framework services (MVC, etc.) being present.

**Comment by SuheylZ** [comment]
yes I did

```
 public static class CoravelStartup
    {

        public static void Configure(IServiceCollection sc, IConfiguration config)
        {
            sc.AddCoravelPro(typeof(CoravelContext));

            var cnn = config.GetValue<string>("storage:coravel");
            sc.AddDbContext<CoravelContext>(options => options.UseSqlServer(cnn));
            sc.AddTransient<IHasPermission, CoravelPermissions>();

            //sc.AddTransient<CoravelContext>( sp => CoravelContext.GetInstance(cnn));
        }

        public static void Configure(IApplicationBuilder app)
        {
            app.UseCoravelPro();
            
            //app.ApplicationServices.UseScheduler(s => { });
        }

    }
```


```
 public class CoravelPermissions: IHasPermission
    {
        public bool HasPermission(HttpRequest request, ClaimsPrincipal claimsPrincipal)
        {
            return true;
        }
    }
```

**Comment by jamesmh** [comment]
Try removing the permissions for now, does that work? Also, is this .NET Core 2 or 3? .NET Core 3 isn't supported yet (soon - working on it)

**Comment by SuheylZ** [comment]
Nope. it doesn't I added permission when I observed the 401 error
the project is aspnetcore 2.1

**Comment by jamesmh** [comment]
Ahh just realized that this is a web API project. Coravel Pro needs the razor page stuff enabled.

In 2.1 you would use` services.AddMvc();` and `app.UseMVC()` to enable it (called before the coravel methods).

In. 3.0 and higher there's a more nuanced method (e.g. `AddRazorPages()`) if you ever need to migrate to 3.0+.

**Comment by jamesmh** [comment]
If you don't want to add MVC to your webApi, then creating a separate project would work. Let me know how things go.

**Comment by SuheylZ** [comment]
I created a separate app using core 3.1 with MVC support. Here is how my code is organized:

```
public class Startup
    {
        readonly Container _container;
        readonly IConfiguration _config;

        public Startup(IConfiguration configuration)
        {
            _config = configuration;
            _container = new SimpleInjector.Container();
            _container.Options.DefaultLifestyle = new SimpleInjector.Lifestyles.AsyncScopedLifestyle();
            _container.Options.ResolveUnregisteredConcreteTypes = false;

        }

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllersWithViews();
            services.AddSimpleInjector(_container, op => 
                op
                .AddAspNetCore()
                .AddControllerActivation()
                .AddViewComponentActivation()
                .AddPageModelActivation()
                .AddTagHelperActivation()
            );

            services
                .AddRazorPages()
                .AddNewtonsoftJson();

            var cnn = _config.GetConnectionString("default");
            services.AddDbContext<CoravelContext>(options => options.UseSqlServer(cnn));

            services.AddCoravelPro(typeof(CoravelContext));
            services.AddTransient<IHasPermission, CoravelPermissions>();
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
             app.UseSimpleInjector(_container);

            if (env.IsDevelopment())
                app.UseDeveloperExceptionPage();
            
            app
                .UseStaticFiles()
                .UseRouting()
                .UseAuthorization()
                .UseEndpoints(endpoints =>
                {
                    endpoints.MapControllerRoute(name: "default", pattern: "{controller=Home}/{action=Index}");
                    endpoints.MapControllers();
                });

            app.UseCoravelPro();
            
            _container.Verify();
        }

```
But still I'm not able to access the Coravel/Dashboard.  at _container.Verify() it gives error: 

> System.InvalidOperationException: 'The configuration is invalid. Creating the instance for type DashboardModel failed. Object reference not set to an instance of an object.'

**Comment by jamesmh** [comment]
Coravel Pro doesn't support using a DI container other than the built-in .NET Core container. This could be a possible future feature but having to abstract the container away and build adapters for multiple containers is not in scope right now.

Let me know if you have any other questions.
