### ISSUE TITLE
Error "ScheduleInvocableType must be passed in a type that implements IInvocable."

### ISSUE THREAD

**Issue by ervea** [jamesmh/coravelpro#27]
I can't get Coravel Pro working for a ASP.NET Core 3.1 web app. (Start new project...)

- ASP.NET Core 3.1
- Coravel.Pro (2.0.0) (I also tried older versions)
- Coravel (3.2.0)  (I also tried older versions)
- Microsoft.AspNetCore.Identity.EntityFrameworkCore (3.1.1)
- Microsoft.EntityFrameworkCore.SqlServer (3.1.1)

`public class TestJob : IInvocable
    {
        public Task Invoke()
        {
            Console.WriteLine("Test");
            return Task.CompletedTask;
        }
    }`

`public void ConfigureServices(IServiceCollection services)
        {
            services.AddRazorPages().AddNewtonsoftJson();

            services.AddDbContext<ApplicationDbContext>(options => {
                options.UseSqlServer(Configuration.GetConnectionString("MyConnection"));
            });

            services.AddTransient<TestJob>();

            services.AddScheduler();

            services.AddCoravelPro(typeof(ApplicationDbContext));
        }`

`public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
            }

            app.UseStaticFiles();

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapRazorPages();
            });

            var provider = app.ApplicationServices;
            provider.UseScheduler(scheduler =>
            {
                scheduler.Schedule<TestJob>()
                    .EveryTenMinutes();
            });
            
            app.UseCoravelPro();
        }`

Error on app.UseCoravelPro() : ScheduleInvocableType must be passed in a type that implements IInvocable.

**Comment by jamesmh** [comment]
Try remove `AddScheduler()`. See the docs for more about that: https://www.docs.pro.coravel.net/Installation/#basic-configuration

Let me know if that works 👍

**Comment by ervea** [comment]
That didn't help, but when I downgrade dependencies to:
ASP.NET Core (2.1.1)
Coravel.Pro (1.2.0)
Coravel (2.3.0)
Microsoft.AspNetCore.Identity.EntityFrameworkCore (2.1.1)
Microsoft.EntityFrameworkCore.SqlServer (2.1.14)
then it works, so I will use this for now.

**Comment by jamesmh** [comment]
Hmm, Coravel Pro 2.0.0 should work with .NET Core 3.1. Would you be able to replicate that issue and send me the project?

**Comment by ervea** [comment]
Sure.
[CoravelMvcAppTest.zip](https://github.com/jamesmh/coravelpro/files/4134498/CoravelMvcAppTest.zip)

**Comment by jamesmh** [comment]
In that project you zipped up to me, you were missing a line:

```csharp
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
                endpoints.MapRazorPages(); // MISSING THIS LINE
            });
```

I also had to add a new ef migration.

**Comment by jamesmh** [comment]
![image](https://user-images.githubusercontent.com/7213174/73748434-d7561780-472f-11ea-8af8-3a90b8edfdef.png)

**Comment by ervea** [comment]
It is working now. 👍
Thanks a lot for your quick response.

**Comment by jamesmh** [comment]
Great!
