### ISSUE TITLE
coravel js file dosent load

### ISSUE THREAD

**Issue by yakine-dev** [jamesmh/coravelpro#28]
Hello 
If yous host coravel inside an IIS application like  app.domain.com\host\ whene you open dashboard it try to load  webpack-bundle.js from root <app.domain.com\webpack-bundle.js> instead of <app.domain.com\host\webpack-bundle.js>
and throw a 404

webpack-bundle.js:1 Failed to load resource: the server responded with a status of 404

**Comment by jamesmh** [comment]
Thanks for pointing this out. Will let you know when theres some progress 😀

**Comment by jamesmh** [comment]
2.1.1 should fix that issue. Certain fonts may not work but that's something that can be endured for now vs no js.

**Comment by yakine-dev** [comment]
The js file probleme is fixed but the menu link point to wrong  location 
exemple https://app.domain.com/coravel/jobs instead of https://app.domain.com/host/coravel/jobs
Manuel navigation work
and the logo also dosent load like font file

**Comment by jamesmh** [comment]
Ok thanks, I'll have to fix those too.

**Comment by yakine-dev** [comment]
after another test i found that all the  post and get request point to wrong  url like the button for running a job or https://app.domain.com/coravel/Scheduling?handler=GetHistory

**Comment by jamesmh** [comment]
Ya, IIS sub-applications are a pain. I'll see if I can get some of these fixed.

**Comment by muhammetsahin** [comment]
Same issue,
but no sub-app 

![image](https://user-images.githubusercontent.com/2045788/88522186-ada2ec80-cffe-11ea-8aad-784446652688.png)

![image](https://user-images.githubusercontent.com/2045788/88522233-c14e5300-cffe-11ea-8acd-b4c5f30623f1.png)

**Comment by jamesmh** [comment]
@muhammetsahin what version are you using?

**Comment by muhammetsahin** [comment]
v2.1.1

**Comment by jamesmh** [comment]
This is fixed with version 4.0.0 :)
