### ISSUE TITLE
Coravel Pro Admin Dashboard 404

### ISSUE THREAD

**Issue by AliDoganKim** [jamesmh/coravelpro#29]
Hello, I am using Coravel Pro version 2.1.1.
I am using Dotnet Core 3.1.
Admin Dashboard returns 404 even though I have made the following configurations.

Startup.cs => ConfigureServices
services.addcoravelpro (typeof (mydbcontext));

Startup.cs => Configure
  app.usecoravelpro ();

admin dashboard: /Coravel/Dashboard /
There is no problem in creating database. The problem is I can't access the admin panel.

**Comment by jamesmh** [comment]
Thanks Ali. Could you post your startup's `Configure()` method?

**Comment by AliDoganKim** [comment]
of course @jamesmh .

ConfigureServices
```
   services.AddDbContext<CrawlerDbContext>(options =>
       options.UseNpgsql(Configuration.GetConnectionString("DefaultConnection"),
       b => b.MigrationsAssembly("test06")));
            services.AddCoravelPro(typeof(CrawlerDbContext));
            services.AddControllers();

```
Configure
```
   if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHttpsRedirection();

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
            app.UseCoravelPro();
```

**Comment by jamesmh** [comment]
Please take a look at the documentation for using .NET Core 3.0+

https://www.docs.pro.coravel.net/Installation/#basic-configuration

You'll have to add support for razor pages  + newtonsoft.

You might have to modify the endpoint configuration too and call `endpoints.MapRazorPages()` also.

**Comment by AliDoganKim** [comment]
Thank you so much. In another try I added razor pages and newtonsoft, but I missed "endpoints.MapRazorPages ()". Thank you very much for your support.
