### ISSUE TITLE
the default metrics are not showing when using AddJsonOptions

### ISSUE THREAD

**Issue by MRebati** [jamesmh/coravelpro#3]
hello, 

I was trying the free version and had a problem that the main application would load but there was no text on metric widgets and the application did not find any job.

the problem was solved when I removed JsonOptions from service collection init.

```cs
services
                .AddMvc()
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
                .AddJsonOptions(options => options.SerializerSettings.ContractResolver = new DefaultContractResolver());
```
into:

```cs
services
                .AddMvc()
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
               // .AddJsonOptions(options => options.SerializerSettings.ContractResolver = new DefaultContractResolver());
```

**Comment by jamesmh** [comment]
Thanks for finding this. Do you need the default contract resolver in your project for something specific you are trying to do?

I suspect it's simply a poco in the codebase that is missing a [Serializable] attribute or something like this though...

**Comment by MRebati** [comment]
thank you for the great job on coravel and coravel.pro projects

right now I'm fine. I just created a new project to control the job managements. and don't need the JsonOptions on this project. just found it and thought it's better to let you know.

good luck 🙏 🌷

**Comment by jamesmh** [comment]
Great - thanks! 👍
