### ISSUE TITLE
[Feature] Set a Timezone for each Job within UI

### ISSUE THREAD

**Issue by ash-grennan** [jamesmh/coravelpro#30]
Hi James,

Thanks for the awesome library, I appreciate this is viable in Coravel standard:

https://docs.coravel.net/Scheduler/#zoned-schedules

However within pro, it would be nice to have a timezone selected when scheduling a job using the UI. 

Thanks

**Comment by jamesmh** [comment]
It already is in the latest preview version. You'll have to explicitly install the version via nuget:

`dotnet add package Coravel.Pro --version 3.0.0-preview2`

You'll have to update the database interface in your EF Core context and generate a migration. Then it should work.

Let me know how it works out for you!

**Comment by ash-grennan** [comment]
Worked perfectly cheers 👌
