### ISSUE TITLE
Provide some info on road map please

### ISSUE THREAD

**Issue by SailorTurkey** [jamesmh/coravelpro#31]
I love your work, came again after 5 months its still just one step short for production use, sadly.

i need at least #12 and  [this](https://github.com/jamesmh/coravel/issues/128) for coravel pro.
For the latter even a generic "string" argument would suffice for starters. I know a generic input would be a pain for front end.

I checked to see if we could schedule INTO CoravelPro using Coravel, but to no avail.

Could you kindly share your thoughts and plans,

Thank you

**Comment by jamesmh** [comment]
If your company is looking to purchase a license for pro, given the pending features are available, let me know. Otherwise, it'll be against other priorities etc. 😅

Just to clarify, you need arguments from the UI?

**Comment by jamesmh** [comment]
Closed issue - issues mentioned have been resolve for a while.
