### ISSUE TITLE
Is EF 3.1 really needed?

### ISSUE THREAD

**Issue by lookingcloudy** [jamesmh/coravelpro#32]
Package restore failed. Rolling back package changes for 'Poseidon.Data'.
Detected package downgrade: Microsoft.Extensions.Configuration from 3.1.5 to 3.1.0. Reference the package directly from the project to select a different version. 
 Poseidon.Data -> Microsoft.EntityFrameworkCore 3.1.5 -> Microsoft.Extensions.Logging 3.1.5 -> Microsoft.Extensions.Configuration.Binder 3.1.5 -> Microsoft.Extensions.Configuration (>= 3.1.5) 
 Poseidon.Data -> Microsoft.Extensions.Configuration (>= 3.1.0)

**Comment by jamesmh** [comment]
What version of coravel pro?

**Comment by jamesmh** [comment]
Sounds like the fix for now is for you to include `Microsoft.Extensions.Configuration` 3.1.5 explicitly in your project? Does that work?

**Comment by lookingcloudy** [comment]
We resolved this by upgrading some other libraries.  Not ideal, but was able to work around this.
