### ISSUE TITLE
Middleware error

### ISSUE THREAD

**Issue by lookingcloudy** [jamesmh/coravelpro#35]
We use middleware to log requests to our system.  Our middleware class constructor looks like:

```        
public RequestLoggerMiddleware(RequestDelegate next, ILoggerFactory loggerFactory, IConfiguration configuration)
        {
            _next = next;
            _logger = loggerFactory.CreateLogger<RequestLoggerMiddleware>();
            _configuration = configuration;
            _storageAccount =
                CloudStorageAccount.Parse(_configuration.GetConnectionString("BlobStorage"));
        }

public async Task Invoke(HttpContext context, IDbContextFactory<PoseidonDbContext> dbContextFactory){...}
```

When calling next(), we get the following cast error.  Not sure if this is a Coravel error or a Microsoft problem:

```
 await _next(context);

Unable to cast object of type 'Microsoft.AspNetCore.Mvc.RazorPages.CompiledPageActionDescriptor' to type 'Microsoft.AspNetCore.Mvc.Controllers.ControllerActionDescriptor'.

```

**Comment by jamesmh** [comment]
All the UI screens in Coravel Pro use Razor Pages. 

You might need to create another constructor that conforms to [this interface.](https://docs.microsoft.com/ru-ru/dotnet/api/microsoft.aspnetcore.mvc.razorpages.compiledpageactiondescriptor.-ctor?view=aspnetcore-3.1)

But, have never come across this so not 100% sure...

**Comment by lookingcloudy** [comment]
Hmmm - we don't use razor pages.  This is an API only project.  I'll do some digging as well.

**Comment by lookingcloudy** [comment]
I removed our middleware class and still received the same error:

`System.InvalidCastException: Unable to cast object of type 'Microsoft.AspNetCore.Mvc.RazorPages.CompiledPageActionDescriptor' to type 'Microsoft.AspNetCore.Mvc.Controllers.ControllerActionDescriptor'.`

**Comment by lookingcloudy** [comment]
It looks like error is only generated when switching to the /Scheduling page.  It does not throw when navigating between /Jobs and /Dashboard.

**Comment by jamesmh** [comment]
Closing - LMK if help is needed.
