### ISSUE TITLE
Exception on second and subsequent requests to Completed panel at Coravel/Scheduling 

### ISSUE THREAD

**Issue by jadkisson** [jamesmh/coravelpro#38]
The first time I open /Coravel/Scheduling, I can see the completed job history. Subsequent page refreshes or paging in the completed panel cause the exception below. Every other feature works fine and the history is being written to the DB. Framework is 3.1 Core and EF is 3.1.7, DB is SQL Server 2019. I had the same issue with EF 3.1.5 as well. The scheduler is working fine and creating new jobs is fine. Any assistance is appreciated.

Exception is caused from ScheduledJobHistoryQuery.GetHistory(Int32 page).

Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a quer
y for context type 'Platform.CustApp.Persistence.Context.AppDbConte
xt'.
      System.InvalidOperationException: BeginExecuteReader requires an
 open and available Connection. The connection's current state is clos
ed.
         at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataRead
erAsync>b__169_0(Task`1 result)
         at System.Threading.Tasks.ContinuationResultTaskFromResultTas
k`2.InnerInvoke()
         at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object ob
j)
         at System.Threading.ExecutionContext.RunInternal(ExecutionCon
text executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location where exception wa
s thrown ---
         at System.Threading.ExecutionContext.RunInternal(ExecutionCon
text executionContext, ContextCallback callback, Object state)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& c
urrentTaskSlot, Thread threadPoolThread)
      --- End of stack trace from previous location where exception wa
s thrown ---
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.Ex
ecuteReaderAsync(RelationalCommandParameterObject parameterObject, Can
cellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.Ex
ecuteReaderAsync(RelationalCommandParameterObject parameterObject, Can
cellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.Ex
ecuteReaderAsync(RelationalCommandParameterObject parameterObject, Can
cellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnume
rable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean res
ult, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.S
qlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, F
unc`4 operation, Func`4 verifySucceeded, CancellationToken cancellatio
nToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnume
rable`1.AsyncEnumerator.MoveNextAsync()
System.InvalidOperationException: BeginExecuteReader requires an open
and available Connection. The connection's current state is closed.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsyn
c>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.In
nerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext e
xecutionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thro
wn ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext e
xecutionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& current
TaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thro
wn ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteR
eaderAsync(RelationalCommandParameterObject parameterObject, Cancellat
ionToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteR
eaderAsync(RelationalCommandParameterObject parameterObject, Cancellat
ionToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteR
eaderAsync(RelationalCommandParameterObject parameterObject, Cancellat
ionToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`
1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, C
ancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServ
erExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4
operation, Func`4 verifySucceeded, CancellationToken cancellationToken
)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`
1.AsyncEnumerator.MoveNextAsync()
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewar
e[1]
      An unhandled exception has occurred while executing the request.

System.InvalidOperationException: BeginExecuteReader requires an open
and available Connection. The connection's current state is closed.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsyn
c>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.In
nerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext e
xecutionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thro
wn ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext e
xecutionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& current
TaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thro
wn ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteR
eaderAsync(RelationalCommandParameterObject parameterObject, Cancellat
ionToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteR
eaderAsync(RelationalCommandParameterObject parameterObject, Cancellat
ionToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteR
eaderAsync(RelationalCommandParameterObject parameterObject, Cancellat
ionToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`
1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, C
ancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServ
erExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4
operation, Func`4 verifySucceeded, CancellationToken cancellationToken
)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`
1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions
.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellat
ionToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions
.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellat
ionToken)
   at Coravel.Pro.Features.Jobs.UseCases.ScheduledJobHistoryQuery.GetH
istory(Int32 page)
   at Coravel.Pro.Coravel.Pages.SchedulingModel.OnPostGetHistory(GetHi
storyModel model)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFacto
ry.GenericTaskHandlerMethod.Convert[T](Object taskAsObject)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFacto
ry.GenericTaskHandlerMethod.Execute(Object receiver, Object[] argument
s)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInv
oker.InvokeHandlerMethodAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInv
oker.InvokeNextPageFilterAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInv
oker.Rethrow(PageHandlerExecutedContext context)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInv
oker.Next(State& next, Scope& scope, Object& state, Boolean& isComplet
ed)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInv
oker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeN
extResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTa
sk, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(
ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(Sta
te& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeF
ilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastT
ask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeA
sync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__Await
RequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invok
e(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Inv
oke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContex
t context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContex
t context)
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContex
t context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfi
lerMiddleware.cs:line 105
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewar
e.Invoke(HttpContext context)

**Comment by jamesmh** [comment]
Looks like the issues is coming from `C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfi
lerMiddleware.cs:line 105`

Try removing mini profiler and see if that works? If so then something in that file is potentially causing the issue 🤔

Let me know what you find 👍

**Comment by jamesmh** [comment]
There was a related bug that's fixed in version 4.0.2 (just released). I highly suspect the bug would have caused this issue too. I'll close this. If this happens again on 4.0.2+ let me know.
