### ISSUE TITLE
How to use with Load balanced UI, windows service

### ISSUE THREAD

**Issue by jadkisson** [jamesmh/coravelpro#39]
It appears Pro starts the scheduler by default in an ASPNET Core application. That makes load balancing a problem. Is there an approach to using the UI (which is very useful and timesaving) along with activating the EF scheduler function in a Windows service? The docs don't mention this approach, but perhaps there is a workaround?

> Coravel Pro uses Coravel's Scheduling, Queuing and Event features under-the-covers. There's therefore no need to call AddScheduler, AddQueue and AddEvents. They should be removed if they exist.

**Comment by jamesmh** [comment]
Not at the moment. 

It's an issue I've been wanting to address in different ways.

1. Using a distributed scheduler (using a distributed lock to make sure only one scheduled task runs when multiple instances are running)
2. What you've suggested: An option to "turn schedule processing on or off" <-- this would apply to coravel pro only though.

I'll look at creating a way to do no. 2 and let you know.
