### ISSUE TITLE
DateTime issue

### ISSUE THREAD

**Issue by MRebati** [jamesmh/coravelpro#4]
hello, 
I've been working on the project and found out the datetime is not setting from the server datetime. how can I handle it? it's not UTC. what time zone is it on?

**Comment by jamesmh** [comment]
Is there a specific feature you were having issues with?

**Comment by MRebati** [comment]
on job history I saw it. and as I'm running on localhost I think it must be my computer's dateTime.
![image](https://user-images.githubusercontent.com/11202543/59707078-1c682080-9217-11e9-8e19-de6bc20483dd.png)

and another issue I'm having is the first item in the list. which has started yesterday and hasn't finished or failed

**Comment by jamesmh** [comment]
I'm sure about the dates yet, I'll have to look into it.

The job that is still running...sounds like the process hosting the .NET Core app was killed prematurely or something like that. I'll have to look into replicating it 🤪

For now, there's a DB table that coravel creates for the job history. If you just put a date in the "end time" or delete that row it'll be a temp fix.

Thanks!

**Comment by jamesmh** [comment]
I'll keep this open since I will be taking a look into the two issues 👍

**Comment by jamesmh** [comment]
I fixed both of these issues. I create another one for the "never-ending" job.

The date logic was incorrect and now shows in "actual" UTC.

Should be part of release 1.2.0 once out of preview 👍

![image](https://user-images.githubusercontent.com/7213174/60357341-c3805100-99a9-11e9-8b03-2ab12da1cc10.png)

**Comment by MRebati** [comment]
Thank you so much

**Comment by jamesmh** [comment]
1.2.0 is live
