### ISSUE TITLE
Entity Framework Dependency in Pro Package

### ISSUE THREAD

**Issue by sbosell** [jamesmh/coravelpro#41]
First, I recently started using your scheduling library and it was really easy to setup and get working so thanks!  Highly recommend.

My question or maybe suggestion is to reconsider the dependency on Entity Framework for the pro package.  I think there are other single file(or small otherwise) orm's that could be used.  We don't use EF in any of or projects and I'm just not keen on adding that dependency.

Dapper is an example, there are others out there as well.

**Comment by biapar** [comment]
I think that without EF, it's not possible to scaffold db

**Comment by jamesmh** [comment]
Closing - at this point EF core support is necessary.
