### ISSUE TITLE
Why Schedule Workers are excluded from Coravel.Pro?

### ISSUE THREAD

**Issue by RaddedSpiritWeaver** [jamesmh/coravelpro#42]
I have been looking around Coravel pros features and can seem to find how can I schedule a job with the UI on a dedicated worker/thread.

I'm amazed that such an amazing and useful feature exists in the open-source package and not the paid version of Coravel.

**Comment by jamesmh** [comment]
Thanks 🙂 That is correct, schedule workers aren't available from the UI in Coravel Pro. As with any software product or project, there can be many reasons why certain features aren't available - time, customer needs, etc.

**Comment by jamesmh** [comment]
This is supported in 5.0.0 now 😊
