### ISSUE TITLE
Prevent Job from Queuing Multiple Times

### ISSUE THREAD

**Issue by kirby14** [jamesmh/coravelpro#43]
It would be helpful if the "Run" button for a job would no longer be active after a job is ran and before it is completed. Currently it will just queue up multiple runs.

A work around for now is to use the "breaking change" popup so someone can't accidently click it twice.

**Comment by jamesmh** [comment]
There are use-cases when someone wants to queue up the same invocable multiple times. Not sure how to support both scenarios...any ideas?

**Comment by kirby14** [comment]
For my use case, another interface like IDestructive that would instead not allow re-queuing would work. I can imagine some people might want to be able to do that based on code but for me, it would be a static option.

Using IDestructive does keep someone from clicking Run twice by accident but it doesn't help the impatient person that thinks they didn't actually get the job kicked off. Maybe the user just needs better/faster feedback. If the Recent job list populated the job and showed Queued as soon as Run is clicked, that would provide the information needed. Then the list could continue to update every 20 seconds after that.

For now we're just in the testing/dev phase and working around it by just putting IDestructive on everything, so this isn't a huge issue.

Thanks!

**Comment by jamesmh** [comment]
Curious if this is still an issue?

**Comment by kirby14** [comment]
The project we were going to use this for was canceled so I haven't had a chance to use it any more. I don't know if this is still a problem, though.

**Comment by jamesmh** [comment]
Thank you for getting back to me 🙂.
