### ISSUE TITLE
Scheduled Jobs status is success when running 

### ISSUE THREAD

**Issue by massimomannoni** [jamesmh/coravelpro#45]
Hi I found a strange behavious using coravel-pro
Having scheduled a job at 1 min, the status is marked as "successful" while the task is still running.
The test is pretty simple. Create a project with un invocable and create a for loop that is called when job is invoked, maybe using a thread.sleep.

As you can see in output is reported the x value loop and in the interface I already have 2 job completed but what is strange is that the first instance is still running ... 
Is there anything I didn't' understood well ? thanks MM

<img width="1299" alt="Schermata 2021-03-23 alle 15 35 33" src="https://user-images.githubusercontent.com/4159719/112163831-ae236f80-8bed-11eb-9c58-f05f71913fa7.png">

**Comment by jamesmh** [comment]
Could you post a code sample of an invocable that does this?

Also, which version of Coravel Pro are you using? Which version of Coravel is being used too?

Thanks!

**Comment by jamesmh** [comment]
Version 4.0.2 should fix this. Let me know if there are any further issues. I'll close this for now.
