### ISSUE TITLE
Blazor web assembly, hosted and Coravel Dashboard

### ISSUE THREAD

**Issue by laur3d** [jamesmh/coravelpro#46]
Hello, 

Is there a way to use coravel pro with a blazor (web assembly, hosted ) application? I've tried everything I thought of and didn't manage to make it work. ( Swagger UI via swashbuckle works fine though).

**Comment by jamesmh** [comment]
You would most likey have to use either blazor in the server hosted mode or use blazor in the web assembly hosted mode but have a separate .NET backend appliation/server running that your blazor application can interact with.
