### ISSUE TITLE
Error: No service for type ApplicationDbContext has been registered

### ISSUE THREAD

**Issue by marcosnegrisoli** [jamesmh/coravelpro#47]
I'm testing the application, but I can't run the application. I'm using .net core 3.0 and Coravel.Pro 4.0.2

I'm getting the following error on the line: app.UseCoravelPro(): No service for type ApplicationDbContext has been registered

Can you help me?

My code: Startup.cs

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddRazorPages();
            services.AddRazorPages().AddNewtonsoftJson();
            services.AddCoravelPro(typeof(ApplicationDbContext));
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseRouting();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapRazorPages();
            });
            app.UseCoravelPro();
        }

        public class ApplicationDbContext : IdentityDbContext, ICoravelProDbContext
        {
            public DbSet<CoravelJobHistory> Coravel_JobHistory { get; set; }
            public DbSet<CoravelScheduledJob> Coravel_ScheduledJobs { get; set; }
            public DbSet<CoravelScheduledJobHistory> Coravel_ScheduledJobHistory { get; set; }
        }

**Comment by marcosnegrisoli** [comment]
Researching a little more I found how to configure the database.

Question: Does the process not create the tables automatically?


        public void ConfigureServices(IServiceCollection services)
        {
            services.AddRazorPages();
            services.AddRazorPages().AddNewtonsoftJson();

            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseNpgsql("server=xxxx;database=xxxx;UID=xxxx;PWD=xxxx")
            );

            services.AddCoravelPro(typeof(ApplicationDbContext));
        }

**Comment by jamesmh** [comment]
No, the database stuff is handled by Entity Framework Core. Coravel Pro just hooks into what EF Core already handles/supports.

So using efcore you'd need to generate migrations, apply them, etc.

**Comment by jamesmh** [comment]
Closing. LMK if help is needed.
