### ISSUE TITLE
question: how is scheduling work?

### ISSUE THREAD

**Issue by MRebati** [jamesmh/coravelpro#7]
Hi, I had an issue when I have a job scheduled to run every hour and my app restarts 3 times in an hour.

does coravel scheduling engine run on every startup and run every job, start every scheduling from that time? or it does check the last ran job in database and run based on previous records?

**Comment by jamesmh** [comment]
Coravel uses a cron-like mechanism. So an hourly schedule will run _on the hour_. So, at 1pm, 2pm, 3pm etc.

**Comment by jamesmh** [comment]
Restarting the app shouldn't cause a schedule to run unless it's due

**Comment by MRebati** [comment]
Thank you so much for the reply. and I had another issue with scheduling jobs in coravel pro panel. 
is it possible to add a string to set the CRON style text for more customized scenarios?

**Comment by jamesmh** [comment]
Not yet lol Could be a future feature.
